### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by jackcarlisle** [dwyl/feedback#34]
We will need to deploy the application to heroku so that it can be hosted and used once ready.

- [ ] ensure application is deployed and working
- [ ] create subdomain `feedback.dwyl.com`

**Comment by nelsonic** [comment]
@jackcarlisle do you have time to do the deployment?
I'm thinking we should use a _sub-domain_ e.g: feedback.dwyl.com ?
created app: https://dashboard.heroku.com/apps/lefeedback added you.
Let me know if you need anything from me to get this deployed. thanks!
(_p.s. please update the issue description above to have a checklist. thanks!_)

**Comment by nelsonic** [comment]
Could we add a link and screenshot to the readme...?
https://dwyl-feedback.herokuapp.com
![image](https://user-images.githubusercontent.com/194400/44026238-4955d5ea-9eea-11e8-86b1-7e26ae69ea72.png)
