### ISSUE TITLE
Subdomain

### ISSUE THREAD

**Issue by jackcarlisle** [dwyl/feedback#76]
We need to link up the application to a dwyl subdomain. Suggestions: `feedback.dwyl.io`

- [x] hook up feedback application to dwyl subdomain

**Comment by iteles** [comment]
Let @markwilliamfirth know what you need on the domain side, he has access to our provider!

**Comment by ghost** [comment]
Update: feedback.dwyl.io and feedback.dwyl.com subdomains added - waiting for propagation

**Comment by jackcarlisle** [comment]
@markwilliamfirth just checked the subdomains and they are working now, closing
